spring.application.name=SpringRestAPI
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/Mohammad Rashid/OneDrive/Desktop/Spring-Boot/db
spring.datasource.username=rashidDB
spring.datasource.password=Rashid123
spring.jpa.hibernate.ddl-auto=update